# Generated by Django 4.2.5 on 2023-10-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_career_carrier_rename_career_package_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='B62CEE8C16E1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='FC730A066756', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number',
            field=models.CharField(default='8C713CF29E1A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='PurchaseOrdernumber',
            field=models.CharField(default='0004B7D1B3DB', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesOrdernumber',
            field=models.CharField(default='CE2A7D9FCA4E', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_number',
            field=models.CharField(default='FBE4DBD132FC', max_length=50, unique=True),
        ),
    ]
