# Generated by Django 4.2.5 on 2023-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_bill_bill_number_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='EBE3968490DD', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='105962EFED09', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number',
            field=models.CharField(default='D88A95219E69', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='PurchaseOrdernumber',
            field=models.CharField(default='C19D301F52CA', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesOrdernumber',
            field=models.CharField(default='2082A4D5566D', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_number',
            field=models.CharField(default='C351B8858344', max_length=50, unique=True),
        ),
    ]
