# Generated by Django 4.2.5 on 2023-10-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_bill_bill_number_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, max_length=10)),
                ('total_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Vendor',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Warehouse',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='PurchaseOrdernumber',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(default='D10725D77CF8', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total_no_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='842CC3B4D4A0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='04678F90909B', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='3BCDA0953C08', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number',
            field=models.CharField(default='2CC27EEC3359', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesOrdernumber',
            field=models.CharField(default='64C82C6DB339', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_number',
            field=models.CharField(default='4E20D4A23288', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(through='inventory.PurchaseOrderProduct', to='inventory.product'),
        ),
    ]
