# Generated by Django 4.2.3 on 2023-10-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorderproduct_rename_phone_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='184A30CC630A', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(through='inventory.BillItem', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='5498092A978D', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(through='inventory.InvoiceItem', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_number',
            field=models.CharField(default='6FA5D4117308', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(default='7315DA01456C', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SalesOrdernumber',
            field=models.CharField(default='7D6FD9D7AA20', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='items',
            field=models.ManyToManyField(through='inventory.SalesOrderItem', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_number',
            field=models.CharField(default='F7BBB55AB7FF', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
