# Generated by Django 4.2.5 on 2023-10-13 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_bill_bill_number_alter_bill_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='package',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='purchase_order',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='items',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='PurchaseOrder',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='Vendor',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='quantity_ordered',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='items',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='SalesOrder',
            new_name='sales_order',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='quantity_ordered',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='items',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='unit_price',
            new_name='total_item_price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Warehouse',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_no_products',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='SalesOrdernumber',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='invoiced',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='packed',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='SalesOrder',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_number',
        ),
        migrations.AddField(
            model_name='billitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='total_item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salesorder'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(default='BL-be03', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default='CO-d12f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default='INV-a4a3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='PR-0a74', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.UUIDField(default='PO-f0ad', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.UUIDField(default='PO-f2d4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Invoiced', 'Invoiced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default='VD-18b6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='contact',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default='WH-2937', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderProduct',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.bill'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.invoice'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='products',
            field=models.ManyToManyField(through='inventory.PurchaseOrderItem', to='inventory.product'),
        ),
    ]
