# Generated by Django 4.2.5 on 2023-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseorderitem_remove_package_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.UUIDField(default='BL-88db', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default='CO-b3ab', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default='INV-6d3e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='PR-4de2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.UUIDField(default='PO-66aa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.UUIDField(default='PO-7865', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.UUIDField(default='VD-a14a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default='WH-de8d', primary_key=True, serialize=False),
        ),
    ]
